# Numpy Pandas 학습 목표


- 배열과 리스트의 차이점
- 배열 생성 다루는 기법
- 기술 통계
- 결과에 대한 분석하는 방법

- 넘파이의 배열은 모든 원소가 같은 자료형이여야 한다.
- resizing X

- Vector(1차원 - 배열) - pandas -> (Series)
- Matrix(2차원 - 행렬) - pandas -> (DataFrame)

- 선형대수(행렬을 이용한 연산 가능)

In [1]:
import numpy as np

- 배열의 차원과 크기, 타입
- ndim, shape, dtype

In [4]:
def aryInfo(ary):
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension : {}'.format(ary.ndim))
    print('dtype : {}'.format(ary.dtype))
    print("Array Data : \n",ary)

## 1차원 배열 생성 
- array()

In [5]:
oneAry = np.array([0,1,2,3,4,5,6,7,8,9])
aryInfo(oneAry)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


- List vs Array 차이점(Vector operation)

In [6]:
data = [0,1,2,3,4,5,6,7,8,9]
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [175]:
# List => 연산이 불가능하다 ex) *2 를 표현하면 리스트의 요소가 2번 반복하게 된다.

# [두번 곱하고 싶으면]
result = []
for d in data :
    result.append(d*2)
print(result)

result2 = [d*2 for d in data]
print(result2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [8]:
# Array를 사용 -> arrary의 operation을 사용하면 훨씬 속도가 빨라짐
result3 = oneAry *2
result3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

- 벡터 연산은 비교, 산술, 논리 연산을 포함하는 모든 수학연산에 적용됨

In [10]:
xAry = np.array([1,2,3])
yAry = np.array([10,20,30])


In [12]:
2* xAry + yAry

array([12, 24, 36])

In [13]:
xAry == 2

array([False,  True, False])

In [14]:
yAry > 20

array([False, False,  True])

In [15]:
(xAry == 2) & (yAry > 20)

array([False, False, False])

## 2차원 배열 생성

- ndarray(N-dimensional Array)
- 1차원 배열이 아닌 다차원 배열 자료구조
- 2차원 배열은 행렬(Matrix)
- list of list -> 2차원
- list of list of list -> 3차원

In [19]:
# 2개의 행과 3개의 열을 가지는 배열을 만들기
twoAry = np.array([[1,2,3],[4,5,6]] , dtype=np.float64)
aryInfo(twoAry)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : float64
Array Data : 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
# 행의 개수 , 열의 개수 
print(len(twoAry)) # 차원
print(len(twoAry[0])) 
print(len(twoAry[1]))

2
3
3


In [21]:
two1Ary = np.array([[1,2,3],[4,5,'6']])
aryInfo(two1Ary)
# dtype -> <U11로 문자열 행렬이 된다.

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : <U11
Array Data : 
 [['1' '2' '3']
 ['4' '5' '6']]


## 3차원 배열 생성

In [24]:
# 2 * 3 * 4 (3행 4열 짜리의 행렬이 2개 있는 3차원 배열)

threeAry = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
aryInfo(threeAry)


type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : int32
Array Data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [30]:
print('dept',len(threeAry)) # 2차원 행렬이 2개라 - 2
print('row',len(threeAry[0]))
print('row[0] col',len(threeAry[0][0])) # 0번째 행렬의 컬럼수  ->1,2,3,4
print('row',len(threeAry[1]))

dept 2
row 3
row[0] col 4
row 3


- 요소의 타입을 변경할 때는 astype()

In [31]:
typeChange = threeAry.astype(np.float64)
aryInfo(typeChange)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : float64
Array Data : 
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]]


In [32]:
indexAry = np.array([1,2,3,4,5,6,7])
aryInfo(indexAry)

type : <class 'numpy.ndarray'>
shape : (7,)
dimension : 1
dtype : int32
Array Data : 
 [1 2 3 4 5 6 7]


In [33]:
indexAry[2]

3

In [34]:
indexAry[-1]

7

In [41]:
# twoAry indexing
# 첫번째 행의 첫번째 열
print(twoAry[0,0])
# 첫번째 행의 두번째 열
print(twoAry[0,1])
# 마지막 행의 마지막 열
print(twoAry[1,-1])

1.0
2.0
6.0


In [44]:
slicingAry = np.array([[1,2,3,4],[5,6,7,8]])

# 첫번째 행의 전체
print(slicingAry[0])
# 두번째 열의 전체
print(slicingAry[:,1])
# 두번째 행의 두번째 열부터 끝까지
print(slicingAry[1,1:])

[1 2 3 4]
[2 6]
[6 7 8]


In [46]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

aryInfo(m)

type : <class 'numpy.ndarray'>
shape : (3, 5)
dimension : 2
dtype : int32
Array Data : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [58]:
# 이 행렬에서 값 7을 인덱싱한다.
print(m[1,2])

# 이 행렬에서 값 14을 인덱싱한다.
print(m[-1,-1])

# 이 행렬에서 값 [6,7]을 인덱싱한다.
print(m[1,1:3])
# 이 행렬에서 값 [7,12]을 인덱싱한다.
print(m[1:,2])
# 이 행렬에서 값 [[3,4].[8,9]]을 인덱싱한다.
print(m[0:2,3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


- fancy indexing : 팬시 인덱싱은 정수나 불린(Boolean) 값을 가지는 다른 Numpy 배열로 배열을 인덱싱할 수 있는 기능을 의미
- boolean indexing

In [61]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
aryInfo(arr)
idx=np.array([True,False,True,False,True,False,True,False,True,False])
print(arr[idx]) # True에 해당하는 idx 번지 추출

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [63]:
arr % 2 # 나머지를 나타내고
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [64]:
arr[arr%2==0] # boolean indexing

array([0, 2, 4, 6, 8])

In [65]:
cntidx =np.array([0,2,4,6,8])
print(arr[cntidx]) 

[0 2 4 6 8]


In [75]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

aryInfo(x)

# 이 배열에서 3의 배수를 찾아라
print(x[x % 3 == 0])

# 이 배열에서 4로 나누면 1이 남는수를 찾아라
print(x[x % 4 == 1])

# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
print(x[(x % 3 == 0)&(x % 4 == 1)])


type : <class 'numpy.ndarray'>
shape : (20,)
dimension : 1
dtype : int32
Array Data : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [77]:
# 배열에 index 배열을 전달하여 배열 요소를 참조해 보자
fancyAry = np.arange(0,12,1).reshape(3,4) # 1차원에서 3행 4열의 2차원행렬이됨
aryInfo(fancyAry)
# reshape -> 배열을 변화 시킴 

type : <class 'numpy.ndarray'>
shape : (3, 4)
dimension : 2
dtype : int32
Array Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [78]:
# 10가져오기
fancyAry[2,2] # scalar 형식

10

In [80]:
# 6가져오기
fancyAry[1:2,2] # 배열형식

array([6])

In [82]:
fancyAry[1:2,1:2] # 2차원 형식

array([[5]])

In [97]:
# 2하고 10
aryInfo(fancyAry[[0,2],2])

type : <class 'numpy.ndarray'>
shape : (2,)
dimension : 1
dtype : int32
Array Data : 
 [ 2 10]


In [98]:
# 2차원으로 출력 -> 배열의 인덱스 번지를 넣어줌
aryInfo(fancyAry[[0,2],2:3])

type : <class 'numpy.ndarray'>
shape : (2, 1)
dimension : 2
dtype : int32
Array Data : 
 [[ 2]
 [10]]


In [183]:
aryInfo(fancyAry[[0,2],[0,2]]) 


type : <class 'numpy.ndarray'>
shape : (2,)
dimension : 1
dtype : int32
Array Data : 
 [ 0 10]


In [188]:
fancyAry[[0,2],[1,1]]

array([1, 9])

In [180]:
rowidx = np.array([0,2])
colidx = np.array([0,2])
print(fancyAry[[rowidx]][:,colidx]) # fancyAry[][]로 가져옴 2차원의 행과 열을 가져옴
print(fancyAry[[[0,2]]][:,[0,2]])

[0 2]
[0 2]
[[ 0  2]
 [ 8 10]]
[[ 0  2]
 [ 8 10]]


## 배열 변형(타입, 형태)

In [122]:
x = np.array([1,2,3],dtype ='U')
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (3,)
dimension : 1
dtype : <U1
Array Data : 
 ['1' '2' '3']


In [123]:
x[0]+x[1]

'12'

- Inf vs NaN

In [125]:
np.array([0,1,-1,0]/np.array([1,0,0,0]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

- zeros [배열의 초기값을 0], ones [배열의 초기값을 1]
- zeros_like [shape만 복사에서 0으로 나타냄 ] 
- ones_like [shape만 복사에서 1으로 나타냄 ]
- empty
- arange [순열]
- linspace , logspace

- zeros : 크기가 정해져 있고 모든 값이 0인 배열을 생성

In [127]:
z = np.zeros(5) # 크기 지정
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : float64
Array Data : 
 [0. 0. 0. 0. 0.]


In [128]:
z = np.zeros((2,3)) # 튜플의 값이 행렬을 뜻한다.
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : float64
Array Data : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [129]:
z = np.zeros(5,dtype='U') 
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : <U1
Array Data : 
 ['' '' '' '' '']


In [132]:
z = np.zeros((2,3),dtype='i') 
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
Array Data : 
 [[0 0 0]
 [0 0 0]]


In [134]:
o = np.ones((2,3,4),dtype='i8') # i:int32 -> i8: int64
aryInfo(o)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : int64
Array Data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [135]:
o_like = np.ones_like(o,dtype='f')
aryInfo(o_like)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : float32
Array Data : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [136]:
z_like = np.zeros_like(z)
aryInfo(z_like)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
Array Data : 
 [[0 0 0]
 [0 0 0]]


In [137]:
e=np.empty((4,3)) # 메모리에 저장된 값으로 배열에 할당되는것이다.(쉽게 말하면 비어있는 프레임)
aryInfo(e)

type : <class 'numpy.ndarray'>
shape : (4, 3)
dimension : 2
dtype : float64
Array Data : 
 [[0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]]


In [139]:
a = np.arange(10) # 0 1 .... n-1
aryInfo(a)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [140]:
a = np.arange(3,21,2) # arange(start,end,step)
aryInfo(a)

type : <class 'numpy.ndarray'>
shape : (9,)
dimension : 1
dtype : int32
Array Data : 
 [ 3  5  7  9 11 13 15 17 19]


- 전치행렬 : 행렬에서 행과 열을 바꾸는 것
- 속성 T 
- transpose operation

In [141]:
arr = np.array([[1,2,3],[4,5,6]])
aryInfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
Array Data : 
 [[1 2 3]
 [4 5 6]]


In [142]:
arr_transpose = arr.T
aryInfo(arr_transpose)

type : <class 'numpy.ndarray'>
shape : (3, 2)
dimension : 2
dtype : int32
Array Data : 
 [[1 4]
 [2 5]
 [3 6]]


In [145]:
# Vector에 Transpose 가능할까? 
vec = np.arange(10)
aryInfo(vec)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [146]:
vec_transpose=vec.T
aryInfo(vec_transpose) # 전치를 할 수 있지만 의미가 없다.

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [148]:
vec_transpose = vec.reshape(1,10).T # 2차원을 만듬
aryInfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10, 1)
dimension : 2
dtype : int32
Array Data : 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


- 배열의 원소를 순차적으로 access 하고자 한다면?
- for (vector, Matrix)
- iterator (iternext(), finish 속성을 이용해서 ndarray 모든 요소를 순차적으로 접근 할 수 있다)

In [149]:
arr = np.array([1,2,3,4,5])
for tmp in arr:
    print(tmp,end=" ") # end=" " 는 한줄로 나오게 한다

1 2 3 4 5 

In [152]:
ite = np.nditer(arr,flags=['c_index']) # 객체를 이용해서 접근할 수 있는 순환방법 
while not ite.finished : # finished 는 순환방법 finish가 되면 true 아니면 false
    print(arr[ite.index],end=" ") # not을 해주어야 finish가 false됨
    ite.iternext()
    
    

1 2 3 4 5 

In [154]:
arr = np.array([[1,2,3],[4,5,6]])
aryInfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
Array Data : 
 [[1 2 3]
 [4 5 6]]


In [173]:
# 2차원 배열에 대한 순차적 요소 나타내기
# arr.shape[0] : 2 -> row
# arr.shape[1] : 3 -> col

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(arr[i][j],end="\t")
    print('\n')

1	2	3	

4	5	6	



In [174]:
ite = np.nditer(arr,flags=['multi_index']) # 2차원
while not ite.finished :
    print(arr[ite.multi_index],end=" ") # not을 해주어야 finish가 false됨
    ite.iternext()

1 2 3 4 5 6 